---
# tasks file for ansible-module-lxd

- name: install lxd
  apt: name={{item}}
       state=present
  with_items:
    - zfsutils-linux
    - lxd
    - lxd-client
    - lxd-tools

- name: verify if /usr/lib/lxd/zfs.img exists
  stat:
    path: /usr/lib/lxd/zfs.img
  register: zfsfile

- name: create zfs file for lxd of 10GB
  command: "truncate -s 10G /usr/lib/lxd/zfs.img"
  when: zfsfile.stat.exists == "False"

- name: create new zpool lxd
  command: "zpool create lxd /usr/lib/lxd/zfs.img"
  when: zfsfile.stat.exists == "False"

- name: configure lxd to use zfs
  command: "lxd init --storage-backend zfs --storage-pool lxd --auto"
  when: zfsfile.stat.exists == "False"

- name: configure lxd bridge
  template: src=lxd-bridge.j2 dest=/etc/default/lxd-bridge mode=0644 backup=yes
  notify:
    - reconfigure lxd
    - restart lxd-bridge
  register: lxdconf

- name: force restart of lxd to have working network
  service: name=lxd state=restarted
  notify:
    - reconfigure lxd
    - restart lxd-bridge
  when: lxdconf.changed and (ansible_virtualization_type is not defined or ansible_virtualization_type != "lxc")

- name: allow remote operations
  command: "{{ lxd_lxc_path }} config set core.https_address {{ lxd_https_listen_address }}"
  when: lxd_allow_remote  

- name: set password for remote operations
  command: "{{ lxd_lxc_path }} config set core.trust_password '{{ lxd_trust_password }}'"
  when: lxd_allow_remote

- name: list existing lxc images
  command: "lxc image list"
  changed_when: false
  register: imagelist

- name: pre copy lxc images
  include: "lxc-image-copy.yml current={{ imagelist }} image={{ item.i }} alias={{ item.alias }}"
  with_items: "{{ lxd_preloadimages }}"

- name: list existing lxc images
  command: "lxc image list"
  changed_when: false
  register: imagelist2

- name: list existing lxc instances
  command: "lxc list"
  changed_when: false
  register: lxclist

- name: preconfigure lxc containers
  include: "lxc-createcontainers.yml guest={{ outer_item.guest }} template={{ outer_item.template }}"
  with_items: "{{ lxd_preconfigure }}"
  loop_control:
    loop_var: outer_item
